version: "3.7"

services:
  dev:
    image: lenikoehler/datenwaben:dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - $PWD/app:/usr/share/nginx/html
  master:
    image: lenikoehler/datenwaben:master
    restart: unless-stopped
    ports:
        - "8001:80"
    volumes:
        - $PWD/app:/usr/share/nginx/html