version: "3.7"

services:
  main:
    image: ./Dockerfile
    restart: unless-stopped
    ports:
        - "8000:80"
    volumes:
        - $PWD/app:/usr/share/nginx/html
  dev:
    image: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - $PWD/app:/usr/share/nginx/html
  dev-leni:
    image: ./Dockerfile
    restart: unless-stopped
    ports:
        - "8008:80"
    volumes:
        - $PWD/app:/usr/share/nginx/html

    dev-benjamin:
      image: ./Dockerfile
      restart: unless-stopped
      ports:
        - "8009:80"
      volumes:
        - $PWD/app:/usr/share/nginx/html

    dev-dennis:
      image: ./Dockerfile
      restart: unless-stopped
      ports:
        - "8010:80"
      volumes:
        - $PWD/app:/usr/share/nginx/html