name: Deploy develop to Linux 2 AMI

on:
  push:
    branches:
      - develop-leni

jobs:
  pull:
    name: pull repo from github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lenikoehler/datenwaben
          path: develop-leni

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          overwrite: true
          rm: true
          source: "./*"
          target: "./datenwaben"