name: Deploy main to Linux 2 AMI

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout main branch
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PEM}}
          port: ${{secrets.PORT}}
          script: |
            echo 'List the running containers: --------------------------------'
            docker container ls
            echo 'Stop the running main containers: ---------------------------'
            docker ps -q --filter ancestor="datenwaben-main" | xargs -r docker stop
            echo 'Show files in git dir: --------------------------------------'
            cd git
            ls
            echo 'Show files in datenwaben dir: -------------------------------'
            cd datenwaben
            ls
            echo 'Git pull from main branch: ----------------------------------'
            git checkout main
            git pull
            echo 'Start main container: ---------------------------------------'
            API_PORT=8008 docker-compose up --build -d node-main
            echo 'List running containers: ------------------------------------'
            docker container ls